# Generated by Django 5.2.6 on 2025-12-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0002_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='mode',
            field=models.CharField(default='active', max_length=7),
        ),
    ]
