# Generated by Django 5.2.6 on 2025-12-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0003_score_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='mode',
            field=models.CharField(max_length=7),
        ),
    ]
