# Generated by Django 5.2.6 on 2025-12-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0004_alter_score_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='image',
            field=models.ImageField(blank=True, default='no.jpg', upload_to='images/'),
        ),
    ]
