# Generated by Django 5.2.6 on 2025-12-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0005_score_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='no.jpg', upload_to='images/'),
        ),
    ]
