# Generated by Django 5.2.6 on 2025-12-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0006_remove_score_image_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='images/no.jpg', upload_to='images/'),
        ),
    ]
