# Generated by Django 5.2.6 on 2026-01-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0016_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='images/default.png', upload_to='images/'),
        ),
    ]
